version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # Prevent local node_modules from overwriting
    environment:
      NODE_ENV: development
      TRACKER_BACKEND_UYA_LIVE_TRACKER_WEBSOCKET_IP: ${TRACKER_BACKEND_UYA_LIVE_TRACKER_WEBSOCKET_IP}


